/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/routes/sort-images/sort-images-master.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/services/log.service';
import * as import9 from '../../../../../src/app/services/mode.service';
import * as import10 from '../../../../../src/app/services/websocket.user.service';
import * as import11 from './sort-images-master.component.css.shim.ngstyle';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import18 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import19 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import20 from '../../../../../src/app/routes/sort-images/sort-images-beamer.component';
import * as import21 from './sort-images-beamer.component.ngfactory';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import25 from '@angular/forms/src/directives/default_value_accessor';
import * as import26 from '@angular/forms/src/directives/number_value_accessor';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_model';
import * as import29 from '@angular/forms/src/directives/ng_control';
import * as import30 from '@angular/forms/src/directives/ng_control_status';
import * as import31 from '@angular/common/src/directives/ng_for';
import * as import32 from '@angular/common/src/directives/ng_if';
export class Wrapper_SortImagesMasterComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SortImagesMasterComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.SortImagesMasterComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_SortImagesMasterComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_SortImagesMasterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SortImagesMasterComponent>;
  _SortImagesMasterComponent_0_3:Wrapper_SortImagesMasterComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SortImagesMasterComponent_Host0,renderType_SortImagesMasterComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'sort-images-master',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SortImagesMasterComponent0(this.viewUtils,this,0,this._el_0);
    this._SortImagesMasterComponent_0_3 = new Wrapper_SortImagesMasterComponent(this.injectorGet(import8.LogService,this.parentIndex),this.injectorGet(import9.ModeService,this.parentIndex),this.injectorGet(import10.WebsocketUserService,this.parentIndex));
    this.compView_0.create(this._SortImagesMasterComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._SortImagesMasterComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SortImagesMasterComponent) && (0 === requestNodeIndex))) { return this._SortImagesMasterComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SortImagesMasterComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._SortImagesMasterComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SortImagesMasterComponentNgFactory:import7.ComponentFactory<import0.SortImagesMasterComponent> = new import7.ComponentFactory<import0.SortImagesMasterComponent>('sort-images-master',View_SortImagesMasterComponent_Host0,import0.SortImagesMasterComponent);
const styles_SortImagesMasterComponent:any[] = [import11.styles];
class View_SortImagesMasterComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SortImagesMasterComponent1,renderType_SortImagesMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_26 = import13.UNINITIALIZED;
    this._expr_27 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-1 col-sm-1 col-xs-1'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-10 col-sm-10 col-xs-10 alert alert-success'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','col-md-8 col-sm-8 col-xs-8'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','col-md-4 col-sm-4 col-xs-4'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n              ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'span',new import3.InlineArray2(2,'class','label label-primary'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n              ',(null as any));
    this._text_19 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_7,'\n          ',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-1 col-sm-1 col-xs-1'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_26:any = import3.inlineInterpolate(1,'\n              ',this.context.$implicit.name,'\n            ');
    if (import3.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setText(this._text_10,currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = import3.inlineInterpolate(1,'\n                  ',this.context.$implicit.pointsRound,'\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setText(this._text_17,currVal_27);
      this._expr_27 = currVal_27;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SortImagesMasterComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SortImagesMasterComponent2,renderType_SortImagesMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'class','btn btn-success','type','button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Set round & round to total',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onClickSetPoints()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_SortImagesMasterComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SortImagesMasterComponent3,renderType_SortImagesMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'\n            ',this.context.$implicit,'\n          ');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_SortImagesMasterComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_SortImagesMasterComponent,{});
export class View_SortImagesMasterComponent0 extends import1.AppView<import0.SortImagesMasterComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _DefaultValueAccessor_39_3:import14.Wrapper_DefaultValueAccessor;
  _NumberValueAccessor_39_4:import15.Wrapper_NumberValueAccessor;
  _NG_VALUE_ACCESSOR_39_5:any[];
  _NgModel_39_6:import16.Wrapper_NgModel;
  _NgControl_39_7:any;
  _NgControlStatus_39_8:import17.Wrapper_NgControlStatus;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _vc_47:import12.ViewContainer;
  _TemplateRef_47_5:any;
  _NgFor_47_6:import18.Wrapper_NgFor;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _anchor_56:any;
  /*private*/ _vc_56:import12.ViewContainer;
  _TemplateRef_56_5:any;
  _NgIf_56_6:import19.Wrapper_NgIf;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _anchor_72:any;
  /*private*/ _vc_72:import12.ViewContainer;
  _TemplateRef_72_5:any;
  _NgFor_72_6:import18.Wrapper_NgFor;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _el_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  compView_87:import1.AppView<import20.SortImagesBeamerComponent>;
  _SortImagesBeamerComponent_87_3:import21.Wrapper_SortImagesBeamerComponent;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SortImagesMasterComponent0,renderType_SortImagesMasterComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fuid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'h2',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_6,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_7,'u',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Sorteer de afbeeldingen',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-md-4'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'h3',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_18,'u',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Manage',(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','form-check form-check-inline'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'label',new import3.InlineArray2(2,'class','form-check-label'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n          ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'input',new import3.InlineArray16(12,'checked','','class','form-check-input','id','inlineRadioSort','name','inlineRadioAction','type','radio','value','sort'),(null as any));
    this._text_27 = this.renderer.createText(this._el_24,' Sorteer\n          ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_24,'input',new import3.InlineArray16(10,'class','form-check-input','id','inlineRadioResult','name','inlineRadioAction','type','radio','value','result'),(null as any));
    this._text_29 = this.renderer.createText(this._el_24,' Resultaat\n        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._text_31 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-md-4 col-sm-3 col-xs-4'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n          Points per image OK:\n        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-md-2 col-sm-2 col-xs-2'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n          ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'input',new import3.InlineArray4(4,'class','form-control','type','number'),(null as any));
    this._DefaultValueAccessor_39_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_39));
    this._NumberValueAccessor_39_4 = new import15.Wrapper_NumberValueAccessor(this.renderer,new import22.ElementRef(this._el_39));
    this._NG_VALUE_ACCESSOR_39_5 = [
      this._DefaultValueAccessor_39_3.context,
      this._NumberValueAccessor_39_4.context
    ]
    ;
    this._NgModel_39_6 = new import16.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_39_5);
    this._NgControl_39_7 = this._NgModel_39_6.context;
    this._NgControlStatus_39_8 = new import17.Wrapper_NgControlStatus(this._NgControl_39_7);
    this._text_40 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_32,'\n      ',(null as any));
    this._text_42 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_15,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_44 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_15,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._anchor_47 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_47 = new import12.ViewContainer(47,15,this,this._anchor_47);
    this._TemplateRef_47_5 = new import23.TemplateRef_(this,47,this._anchor_47);
    this._NgFor_47_6 = new import18.Wrapper_NgFor(this._vc_47.vcRef,this._TemplateRef_47_5,this.parentView.injectorGet(import24.IterableDiffers,this.parentIndex),this.ref);
    this._text_48 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n        ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_49,'div',new import3.InlineArray2(2,'class','col-md-1 col-sm-1 col-xs-1'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_49,'\n        ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_49,'div',new import3.InlineArray2(2,'class','col-md-10 col-sm-10 col-xs-10'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n          ',(null as any));
    this._anchor_56 = this.renderer.createTemplateAnchor(this._el_54,(null as any));
    this._vc_56 = new import12.ViewContainer(56,54,this,this._anchor_56);
    this._TemplateRef_56_5 = new import23.TemplateRef_(this,56,this._anchor_56);
    this._NgIf_56_6 = new import19.Wrapper_NgIf(this._vc_56.vcRef,this._TemplateRef_56_5);
    this._text_57 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._text_58 = this.renderer.createText(this._el_49,'\n        ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_49,'div',new import3.InlineArray2(2,'class','col-md-1 col-sm-1 col-xs-1'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_49,'\n      ',(null as any));
    this._text_62 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_15,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_64 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'\n        ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_65,'div',new import3.InlineArray2(2,'class','col-md-4 col-sm-3 col-xs-4'),(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'\n          Teams with an answer:\n        ',(null as any));
    this._text_69 = this.renderer.createText(this._el_65,'\n        ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_65,'div',new import3.InlineArray2(2,'class','col-md-8 col-sm-9 col-xs-8'),(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'\n          ',(null as any));
    this._anchor_72 = this.renderer.createTemplateAnchor(this._el_70,(null as any));
    this._vc_72 = new import12.ViewContainer(72,70,this,this._anchor_72);
    this._TemplateRef_72_5 = new import23.TemplateRef_(this,72,this._anchor_72);
    this._NgFor_72_6 = new import18.Wrapper_NgFor(this._vc_72.vcRef,this._TemplateRef_72_5,this.parentView.injectorGet(import24.IterableDiffers,this.parentIndex),this.ref);
    this._text_73 = this.renderer.createText(this._el_70,'\n        ',(null as any));
    this._text_74 = this.renderer.createText(this._el_65,'\n      ',(null as any));
    this._text_75 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_76 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-md-1'),(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'\n    ',(null as any));
    this._text_79 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-md-7'),(null as any));
    this._text_81 = this.renderer.createText(this._el_80,'\n      ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_80,'h3',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_82,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_83,'u',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'Beamer',(null as any));
    this._text_86 = this.renderer.createText(this._el_80,'\n      ',(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,this._el_80,'sort-images-beamer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_87 = new import21.View_SortImagesBeamerComponent0(this.viewUtils,this,87,this._el_87);
    this._SortImagesBeamerComponent_87_3 = new import21.Wrapper_SortImagesBeamerComponent(this.parentView.injectorGet(import8.LogService,this.parentIndex),this.parentView.injectorGet(import9.ModeService,this.parentIndex),this.parentView.injectorGet(import10.WebsocketUserService,this.parentIndex));
    this.compView_87.create(this._SortImagesBeamerComponent_87_3.context);
    this._text_88 = this.renderer.createText(this._el_80,'\n    ',(null as any));
    this._text_89 = this.renderer.createText(this._el_13,'\n  ',(null as any));
    this._text_90 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_91 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_26));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_28));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_39,new import3.InlineArray8(8,'ngModelChange',(null as any),'change',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_39));
    this._NgModel_39_6.subscribe(this,this.eventHandler(this.handleEvent_39),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_87,new import3.InlineArray2(2,'teamImagesInfoEvt',(null as any)),this.eventHandler(this.handleEvent_87));
    this._SortImagesBeamerComponent_87_3.subscribe(this,this.eventHandler(this.handleEvent_87),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._anchor_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._anchor_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._anchor_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._el_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.DefaultValueAccessor) && (39 === requestNodeIndex))) { return this._DefaultValueAccessor_39_3.context; }
    if (((token === import26.NumberValueAccessor) && (39 === requestNodeIndex))) { return this._NumberValueAccessor_39_4.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (39 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_39_5; }
    if (((token === import28.NgModel) && (39 === requestNodeIndex))) { return this._NgModel_39_6.context; }
    if (((token === import29.NgControl) && (39 === requestNodeIndex))) { return this._NgControl_39_7; }
    if (((token === import30.NgControlStatus) && (39 === requestNodeIndex))) { return this._NgControlStatus_39_8.context; }
    if (((token === import23.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import31.NgFor) && (47 === requestNodeIndex))) { return this._NgFor_47_6.context; }
    if (((token === import23.TemplateRef) && (56 === requestNodeIndex))) { return this._TemplateRef_56_5; }
    if (((token === import32.NgIf) && (56 === requestNodeIndex))) { return this._NgIf_56_6.context; }
    if (((token === import23.TemplateRef) && (72 === requestNodeIndex))) { return this._TemplateRef_72_5; }
    if (((token === import31.NgFor) && (72 === requestNodeIndex))) { return this._NgFor_72_6.context; }
    if (((token === import20.SortImagesBeamerComponent) && (87 === requestNodeIndex))) { return this._SortImagesBeamerComponent_87_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_39_3.ngDoCheck(this,this._el_39,throwOnChange);
    this._NumberValueAccessor_39_4.ngDoCheck(this,this._el_39,throwOnChange);
    const currVal_39_2_0:any = this.context.pointsPerImageOk;
    this._NgModel_39_6.check_model(currVal_39_2_0,throwOnChange,false);
    this._NgModel_39_6.ngDoCheck(this,this._el_39,throwOnChange);
    this._NgControlStatus_39_8.ngDoCheck(this,this._el_39,throwOnChange);
    const currVal_47_0_0:any = this.context.teamImagesInfo;
    this._NgFor_47_6.check_ngForOf(currVal_47_0_0,throwOnChange,false);
    this._NgFor_47_6.ngDoCheck(this,this._anchor_47,throwOnChange);
    const currVal_56_0_0:any = (0 != this.context.teamImagesInfo.length);
    this._NgIf_56_6.check_ngIf(currVal_56_0_0,throwOnChange,false);
    this._NgIf_56_6.ngDoCheck(this,this._anchor_56,throwOnChange);
    const currVal_72_0_0:any = this.context.teams;
    this._NgFor_72_6.check_ngForOf(currVal_72_0_0,throwOnChange,false);
    this._NgFor_72_6.ngDoCheck(this,this._anchor_72,throwOnChange);
    const currVal_87_0_0:any = false;
    this._SortImagesBeamerComponent_87_3.check_showTitle(currVal_87_0_0,throwOnChange,false);
    this._SortImagesBeamerComponent_87_3.ngDoCheck(this,this._el_87,throwOnChange);
    this._vc_47.detectChangesInNestedViews(throwOnChange);
    this._vc_56.detectChangesInNestedViews(throwOnChange);
    this._vc_72.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatus_39_8.checkHost(this,this,this._el_39,throwOnChange);
    this.compView_87.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_47.destroyNestedViews();
    this._vc_56.destroyNestedViews();
    this._vc_72.destroyNestedViews();
    this.compView_87.destroy();
    this._NgModel_39_6.ngOnDestroy();
    this._SortImagesBeamerComponent_87_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 47)) { return new View_SortImagesMasterComponent1(this.viewUtils,this,47,this._anchor_47,this._vc_47); }
    if ((nodeIndex == 56)) { return new View_SortImagesMasterComponent2(this.viewUtils,this,56,this._anchor_56,this._vc_56); }
    if ((nodeIndex == 72)) { return new View_SortImagesMasterComponent3(this.viewUtils,this,72,this._anchor_72,this._vc_72); }
    return (null as any);
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickRadioAction(true)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickRadioAction(false)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_39(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_39_3.handleEvent(eventName,$event) && result);
    result = (this._NumberValueAccessor_39_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.pointsPerImageOk = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'change')) {
      const pd_sub_1:any = ((<any>this.context.onPointsPerImageChange($event.target.value)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_87(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'teamImagesInfoEvt')) {
      const pd_sub_0:any = ((<any>this.context.handleTeamImagesInfoEvt($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}