/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.layout[_ngcontent-%COMP%] {\r\n    padding: 25px;\r\n    margin: 25px;\r\n}'];