/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/routes/sort-images/sort-images-beamer.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../../../src/app/services/log.service';
import * as import10 from '../../../../../src/app/services/mode.service';
import * as import11 from '../../../../../src/app/services/websocket.user.service';
import * as import12 from './sort-images-beamer.component.css.shim.ngstyle';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '../../../../../src/app/components/image-local/image-local.component';
import * as import15 from '../../components/image-local/image-local.component.ngfactory';
import * as import16 from '../../../../../src/app/services/cloud.service';
import * as import17 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/common/src/directives/ng_for';
import * as import21 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import22 from '@angular/common/src/directives/ng_if';
export class Wrapper_SortImagesBeamerComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SortImagesBeamerComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  subscription0:any;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.SortImagesBeamerComponent(p0,p1,p2);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_showTitle(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.showTitle = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.teamImagesInfoEvt.subscribe(_eventHandler.bind(view,'teamImagesInfoEvt'))); }
  }
}
var renderType_SortImagesBeamerComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_SortImagesBeamerComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.SortImagesBeamerComponent>;
  _SortImagesBeamerComponent_0_3:Wrapper_SortImagesBeamerComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SortImagesBeamerComponent_Host0,renderType_SortImagesBeamerComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'sort-images-beamer',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SortImagesBeamerComponent0(this.viewUtils,this,0,this._el_0);
    this._SortImagesBeamerComponent_0_3 = new Wrapper_SortImagesBeamerComponent(this.injectorGet(import9.LogService,this.parentIndex),this.injectorGet(import10.ModeService,this.parentIndex),this.injectorGet(import11.WebsocketUserService,this.parentIndex));
    this.compView_0.create(this._SortImagesBeamerComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._SortImagesBeamerComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SortImagesBeamerComponent) && (0 === requestNodeIndex))) { return this._SortImagesBeamerComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SortImagesBeamerComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._SortImagesBeamerComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SortImagesBeamerComponentNgFactory:import8.ComponentFactory<import0.SortImagesBeamerComponent> = new import8.ComponentFactory<import0.SortImagesBeamerComponent>('sort-images-beamer',View_SortImagesBeamerComponent_Host0,import0.SortImagesBeamerComponent);
const styles_SortImagesBeamerComponent:any[] = [import12.styles];
class View_SortImagesBeamerComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_SortImagesBeamerComponent1,renderType_SortImagesBeamerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h2',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_2,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_3,'u',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Sorteer de afbeeldingen',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SortImagesBeamerComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import14.ImageLocalComponent>;
  _ImageLocalComponent_2_3:import15.Wrapper_ImageLocalComponent;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_SortImagesBeamerComponent3,renderType_SortImagesBeamerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'class','layout'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'image-local',new import3.InlineArray4(4,'height','200','width','-2'),(null as any));
    this.compView_2 = new import15.View_ImageLocalComponent0(this.viewUtils,this,2,this._el_2);
    this._ImageLocalComponent_2_3 = new import15.Wrapper_ImageLocalComponent(this.parentView.parentView.parentView.injectorGet(import16.CloudService,this.parentView.parentView.parentIndex));
    this.compView_2.create(this._ImageLocalComponent_2_3.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ImageLocalComponent) && (2 === requestNodeIndex))) { return this._ImageLocalComponent_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.$implicit;
    this._ImageLocalComponent_2_3.check_source(currVal_2_0_0,throwOnChange,false);
    const currVal_2_0_1:any = '200';
    this._ImageLocalComponent_2_3.check_height(currVal_2_0_1,throwOnChange,false);
    const currVal_2_0_2:any = '-2';
    this._ImageLocalComponent_2_3.check_width(currVal_2_0_2,throwOnChange,false);
    this._ImageLocalComponent_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this._ImageLocalComponent_2_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SortImagesBeamerComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _vc_6:import13.ViewContainer;
  _TemplateRef_6_5:any;
  _NgFor_6_6:import17.Wrapper_NgFor;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_SortImagesBeamerComponent2,renderType_SortImagesBeamerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','text-center','id','elements'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_6 = new import13.ViewContainer(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import18.TemplateRef_(this,6,this._anchor_6);
    this._NgFor_6_6 = new import17.Wrapper_NgFor(this._vc_6.vcRef,this._TemplateRef_6_5,this.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_7 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8,
      this._text_9
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import20.NgFor) && (6 === requestNodeIndex))) { return this._NgFor_6_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_6_0_0:any = this.parentView.context.images;
    this._NgFor_6_6.check_ngForOf(currVal_6_0_0,throwOnChange,false);
    this._NgFor_6_6.ngDoCheck(this,this._anchor_6,throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_6.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 6)) { return new View_SortImagesBeamerComponent3(this.viewUtils,this,6,this._anchor_6,this._vc_6); }
    return (null as any);
  }
}
class View_SortImagesBeamerComponent5 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_SortImagesBeamerComponent5,renderType_SortImagesBeamerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_5 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n             ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n           ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:any = import3.inlineInterpolate(1,'\n               ',this.context.$implicit.teamName,'  \n             ');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SortImagesBeamerComponent7 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import2.AppView<import14.ImageLocalComponent>;
  _ImageLocalComponent_4_3:import15.Wrapper_ImageLocalComponent;
  _text_5:any;
  _text_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_SortImagesBeamerComponent7,renderType_SortImagesBeamerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n             ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n               ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'image-local',new import3.InlineArray4(4,'height','200','width','-2'),(null as any));
    this.compView_4 = new import15.View_ImageLocalComponent0(this.viewUtils,this,4,this._el_4);
    this._ImageLocalComponent_4_3 = new import15.Wrapper_ImageLocalComponent(this.parentView.parentView.parentView.parentView.injectorGet(import16.CloudService,this.parentView.parentView.parentView.parentIndex));
    this.compView_4.create(this._ImageLocalComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n             ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n           ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ImageLocalComponent) && (4 === requestNodeIndex))) { return this._ImageLocalComponent_4_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:any = this.context.$implicit.images[0][this.parentView.context.index];
    this._ImageLocalComponent_4_3.check_source(currVal_4_0_0,throwOnChange,false);
    const currVal_4_0_1:any = '200';
    this._ImageLocalComponent_4_3.check_height(currVal_4_0_1,throwOnChange,false);
    const currVal_4_0_2:any = '-2';
    this._ImageLocalComponent_4_3.check_width(currVal_4_0_2,throwOnChange,false);
    const currVal_4_0_3:any = (this.context.$implicit.ok[this.parentView.context.index]? 'image-ok': 'image-error');
    this._ImageLocalComponent_4_3.check_class(currVal_4_0_3,throwOnChange,false);
    this._ImageLocalComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.compView_4.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_4.destroy();
    this._ImageLocalComponent_4_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SortImagesBeamerComponent6 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  compView_6:import2.AppView<import14.ImageLocalComponent>;
  _ImageLocalComponent_6_3:import15.Wrapper_ImageLocalComponent;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _vc_10:import13.ViewContainer;
  _TemplateRef_10_5:any;
  _NgFor_10_6:import17.Wrapper_NgFor;
  _text_11:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_SortImagesBeamerComponent6,renderType_SortImagesBeamerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n           ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n             ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n               ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'image-local',new import3.InlineArray4(4,'height','200','width','-2'),(null as any));
    this.compView_6 = new import15.View_ImageLocalComponent0(this.viewUtils,this,6,this._el_6);
    this._ImageLocalComponent_6_3 = new import15.Wrapper_ImageLocalComponent(this.parentView.parentView.parentView.injectorGet(import16.CloudService,this.parentView.parentView.parentIndex));
    this.compView_6.create(this._ImageLocalComponent_6_3.context);
    this._text_7 = this.renderer.createText(this._el_4,'\n             ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n           ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n           ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_10 = new import13.ViewContainer(10,0,this,this._anchor_10);
    this._TemplateRef_10_5 = new import18.TemplateRef_(this,10,this._anchor_10);
    this._NgFor_10_6 = new import17.Wrapper_NgFor(this._vc_10.vcRef,this._TemplateRef_10_5,this.parentView.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentView.parentIndex),this.parentView.parentView.ref);
    this._text_11 = this.renderer.createText(this._el_0,'\n         ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._anchor_10,
      this._text_11
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ImageLocalComponent) && (6 === requestNodeIndex))) { return this._ImageLocalComponent_6_3.context; }
    if (((token === import18.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import20.NgFor) && (10 === requestNodeIndex))) { return this._NgFor_10_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_6_0_0:any = this.context.$implicit;
    this._ImageLocalComponent_6_3.check_source(currVal_6_0_0,throwOnChange,false);
    const currVal_6_0_1:any = '200';
    this._ImageLocalComponent_6_3.check_height(currVal_6_0_1,throwOnChange,false);
    const currVal_6_0_2:any = '-2';
    this._ImageLocalComponent_6_3.check_width(currVal_6_0_2,throwOnChange,false);
    this._ImageLocalComponent_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    const currVal_10_0_0:any = this.parentView.parentView.context.teams;
    this._NgFor_10_6.check_ngForOf(currVal_10_0_0,throwOnChange,false);
    this._NgFor_10_6.ngDoCheck(this,this._anchor_10,throwOnChange);
    this._vc_10.detectChangesInNestedViews(throwOnChange);
    this.compView_6.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_10.destroyNestedViews();
    this.compView_6.destroy();
    this._ImageLocalComponent_6_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 10)) { return new View_SortImagesBeamerComponent7(this.viewUtils,this,10,this._anchor_10,this._vc_10); }
    return (null as any);
  }
}
class View_SortImagesBeamerComponent8 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_SortImagesBeamerComponent8,renderType_SortImagesBeamerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_11 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n             ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n               ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                 ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'span',new import3.InlineArray2(2,'class','label label-primary'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n               ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n             ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n           ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_11:any = import3.inlineInterpolate(2,'\n                   ',this.context.$implicit.imagesNbrOk,'/',this.context.$implicit.imagesNbrTotal,'\n                 ');
    if (import3.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_7,currVal_11);
      this._expr_11 = currVal_11;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SortImagesBeamerComponent4 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import13.ViewContainer;
  _TemplateRef_15_5:any;
  _NgFor_15_6:import17.Wrapper_NgFor;
  _text_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import13.ViewContainer;
  _TemplateRef_18_5:any;
  _NgFor_18_6:import17.Wrapper_NgFor;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _vc_25:import13.ViewContainer;
  _TemplateRef_25_5:any;
  _NgFor_25_6:import17.Wrapper_NgFor;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_SortImagesBeamerComponent4,renderType_SortImagesBeamerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n       ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'table',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n         ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_6,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n           ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n             ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n               De oplossing\n             ',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n           ',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n           ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._vc_15 = new import13.ViewContainer(15,7,this,this._anchor_15);
    this._TemplateRef_15_5 = new import18.TemplateRef_(this,15,this._anchor_15);
    this._NgFor_15_6 = new import17.Wrapper_NgFor(this._vc_15.vcRef,this._TemplateRef_15_5,this.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_16 = this.renderer.createText(this._el_7,'\n         ',(null as any));
    this._text_17 = this.renderer.createText(this._el_6,'\n         ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_18 = new import13.ViewContainer(18,6,this,this._anchor_18);
    this._TemplateRef_18_5 = new import18.TemplateRef_(this,18,this._anchor_18);
    this._NgFor_18_6 = new import17.Wrapper_NgFor(this._vc_18.vcRef,this._TemplateRef_18_5,this.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_19 = this.renderer.createText(this._el_6,'\n         ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_6,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n           ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n           ',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n           ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._vc_25 = new import13.ViewContainer(25,20,this,this._anchor_25);
    this._TemplateRef_25_5 = new import18.TemplateRef_(this,25,this._anchor_25);
    this._NgFor_25_6 = new import17.Wrapper_NgFor(this._vc_25.vcRef,this._TemplateRef_25_5,this.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_26 = this.renderer.createText(this._el_20,'\n         ',(null as any));
    this._text_27 = this.renderer.createText(this._el_6,'\n       ',(null as any));
    this._text_28 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import20.NgFor) && (15 === requestNodeIndex))) { return this._NgFor_15_6.context; }
    if (((token === import18.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import20.NgFor) && (18 === requestNodeIndex))) { return this._NgFor_18_6.context; }
    if (((token === import18.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import20.NgFor) && (25 === requestNodeIndex))) { return this._NgFor_25_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_15_0_0:any = this.parentView.context.teams;
    this._NgFor_15_6.check_ngForOf(currVal_15_0_0,throwOnChange,false);
    this._NgFor_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    const currVal_18_0_0:any = this.parentView.context.imagesSolution;
    this._NgFor_18_6.check_ngForOf(currVal_18_0_0,throwOnChange,false);
    this._NgFor_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    const currVal_25_0_0:any = this.parentView.context.teams;
    this._NgFor_25_6.check_ngForOf(currVal_25_0_0,throwOnChange,false);
    this._NgFor_25_6.ngDoCheck(this,this._anchor_25,throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this._vc_25.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_15.destroyNestedViews();
    this._vc_18.destroyNestedViews();
    this._vc_25.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 15)) { return new View_SortImagesBeamerComponent5(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    if ((nodeIndex == 18)) { return new View_SortImagesBeamerComponent6(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    if ((nodeIndex == 25)) { return new View_SortImagesBeamerComponent8(this.viewUtils,this,25,this._anchor_25,this._vc_25); }
    return (null as any);
  }
}
var renderType_SortImagesBeamerComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_SortImagesBeamerComponent,{});
export class View_SortImagesBeamerComponent0 extends import2.AppView<import0.SortImagesBeamerComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import13.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import21.Wrapper_NgIf;
  _text_5:any;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _vc_7:import13.ViewContainer;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import21.Wrapper_NgIf;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _vc_9:import13.ViewContainer;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import21.Wrapper_NgIf;
  _text_10:any;
  _text_11:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SortImagesBeamerComponent0,renderType_SortImagesBeamerComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fuid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_4 = new import13.ViewContainer(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import18.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import21.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_7 = new import13.ViewContainer(7,0,this,this._anchor_7);
    this._TemplateRef_7_5 = new import18.TemplateRef_(this,7,this._anchor_7);
    this._NgIf_7_6 = new import21.Wrapper_NgIf(this._vc_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_9 = new import13.ViewContainer(9,0,this,this._anchor_9);
    this._TemplateRef_9_5 = new import18.TemplateRef_(this,9,this._anchor_9);
    this._NgIf_9_6 = new import21.Wrapper_NgIf(this._vc_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_11 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import22.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import18.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import22.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6.context; }
    if (((token === import18.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import22.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:any = this.context.showTitle;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    const currVal_7_0_0:any = this.context.sortImages;
    this._NgIf_7_6.check_ngIf(currVal_7_0_0,throwOnChange,false);
    this._NgIf_7_6.ngDoCheck(this,this._anchor_7,throwOnChange);
    const currVal_9_0_0:boolean = !this.context.sortImages;
    this._NgIf_9_6.check_ngIf(currVal_9_0_0,throwOnChange,false);
    this._NgIf_9_6.ngDoCheck(this,this._anchor_9,throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this._vc_7.detectChangesInNestedViews(throwOnChange);
    this._vc_9.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
    this._vc_7.destroyNestedViews();
    this._vc_9.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 4)) { return new View_SortImagesBeamerComponent1(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    if ((nodeIndex == 7)) { return new View_SortImagesBeamerComponent2(this.viewUtils,this,7,this._anchor_7,this._vc_7); }
    if ((nodeIndex == 9)) { return new View_SortImagesBeamerComponent4(this.viewUtils,this,9,this._anchor_9,this._vc_9); }
    return (null as any);
  }
}