/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/routes/questions/questions-master.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/services/log.service';
import * as import9 from '../../../../../src/app/services/mode.service';
import * as import10 from '../../../../../src/app/services/websocket.user.service';
import * as import11 from './questions.component.css.shim.ngstyle';
import * as import12 from './questions-master.component.css.shim.ngstyle';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import16 from '@angular/core/src/change_detection/change_detection_util';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import19 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import20 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/common/src/directives/ng_if';
import * as import23 from '../../../../../src/app/routes/questions/questions-images.component';
import * as import24 from './questions-images.component.ngfactory';
import * as import25 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import26 from '../../../../node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory';
import * as import27 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import28 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import29 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import30 from '../../../../../src/app/routes/questions/questions-beamer.component';
import * as import31 from './questions-beamer.component.ngfactory';
import * as import32 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import33 from '@angular/forms/src/directives/default_value_accessor';
import * as import34 from '@angular/forms/src/directives/number_value_accessor';
import * as import35 from '@angular/forms/src/directives/control_value_accessor';
import * as import36 from '@angular/forms/src/directives/ng_model';
import * as import37 from '@angular/forms/src/directives/ng_control';
import * as import38 from '@angular/forms/src/directives/ng_control_status';
import * as import39 from '@angular/common/src/directives/ng_for';
export class Wrapper_QuestionsMasterComponent {
  /*private*/ _eventHandler:Function;
  context:import0.QuestionsMasterComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.QuestionsMasterComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_QuestionsMasterComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_QuestionsMasterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.QuestionsMasterComponent>;
  _QuestionsMasterComponent_0_3:Wrapper_QuestionsMasterComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_QuestionsMasterComponent_Host0,renderType_QuestionsMasterComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'questions-master',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_QuestionsMasterComponent0(this.viewUtils,this,0,this._el_0);
    this._QuestionsMasterComponent_0_3 = new Wrapper_QuestionsMasterComponent(this.injectorGet(import8.LogService,this.parentIndex),this.injectorGet(import9.ModeService,this.parentIndex),this.injectorGet(import10.WebsocketUserService,this.parentIndex));
    this.compView_0.create(this._QuestionsMasterComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._QuestionsMasterComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.QuestionsMasterComponent) && (0 === requestNodeIndex))) { return this._QuestionsMasterComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._QuestionsMasterComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._QuestionsMasterComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const QuestionsMasterComponentNgFactory:import7.ComponentFactory<import0.QuestionsMasterComponent> = new import7.ComponentFactory<import0.QuestionsMasterComponent>('questions-master',View_QuestionsMasterComponent_Host0,import0.QuestionsMasterComponent);
const styles_QuestionsMasterComponent:any[] = [
  import11.styles,
  import12.styles
]
;
class View_QuestionsMasterComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent1,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'class','btn btn-info','type','button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Cancel',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onClickSetNumberOfQuestionsCancel()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_QuestionsMasterComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent2,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'class','btn btn-danger','type','button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Confirm',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onClickSetNumberOfQuestionsTwo()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_QuestionsMasterComponent3 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import14.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import15.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent3,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_0_3 = new import14.Wrapper_NgSelectOption(new import17.ElementRef(this._el_0),this.renderer,(<View_QuestionsMasterComponent0>this.parentView)._SelectControlValueAccessor_61_3.context);
    this._NgSelectMultipleOption_0_4 = new import15.Wrapper_NgSelectMultipleOption(new import17.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import19.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit.name;
    this._NgSelectOption_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = this.context.$implicit.name;
    this._NgSelectMultipleOption_0_4.check_value(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_QuestionsMasterComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent4,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-12 col-sm-12 col-xs-12'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n          Punten in deze ronde:\n        ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_QuestionsMasterComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent6,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-md-1 col-sm-1 col-xs-1'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_QuestionsMasterComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent7,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_17 = import16.UNINITIALIZED;
    this._expr_18 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-md-10 col-sm-10 col-xs-10 alert alert-success'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-md-8 col-sm-8 col-xs-8'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-md-4 col-sm-4 col-xs-4'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','label label-primary'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_17:any = import3.inlineInterpolate(1,'\n              ',this.parentView.context.$implicit.name,'\n            ');
    if (import3.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_5,currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = import3.inlineInterpolate(1,'\n                  ',this.parentView.context.$implicit.pointsRound,'\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_12,currVal_18);
      this._expr_18 = currVal_18;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_QuestionsMasterComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent8,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-md-1 col-sm-1 col-xs-1'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_QuestionsMasterComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import13.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import20.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import13.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import20.Wrapper_NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _vc_6:import13.ViewContainer;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import20.Wrapper_NgIf;
  _text_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent5,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import13.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import21.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import20.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_4 = new import13.ViewContainer(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import21.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import20.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_6 = new import13.ViewContainer(6,0,this,this._anchor_6);
    this._TemplateRef_6_5 = new import21.TemplateRef_(this,6,this._anchor_6);
    this._NgIf_6_6 = new import20.Wrapper_NgIf(this._vc_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import22.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import21.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import22.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import21.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import22.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:boolean = !this.parentView.context.modeAnswering;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_4_0_0:boolean = !this.parentView.context.modeAnswering;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    const currVal_6_0_0:boolean = !this.parentView.context.modeAnswering;
    this._NgIf_6_6.check_ngIf(currVal_6_0_0,throwOnChange,false);
    this._NgIf_6_6.ngDoCheck(this,this._anchor_6,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
    this._vc_6.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_QuestionsMasterComponent6(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_QuestionsMasterComponent7(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    if ((nodeIndex == 6)) { return new View_QuestionsMasterComponent8(this.viewUtils,this,6,this._anchor_6,this._vc_6); }
    return (null as any);
  }
}
class View_QuestionsMasterComponent10 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent10,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'class','btn btn-success','type','button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Set round & round to total',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.onClickSetPoints()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_QuestionsMasterComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _vc_7:import13.ViewContainer;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import20.Wrapper_NgIf;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent9,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-1 col-sm-1 col-xs-1'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-10 col-sm-10 col-xs-10'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._vc_7 = new import13.ViewContainer(7,5,this,this._anchor_7);
    this._TemplateRef_7_5 = new import21.TemplateRef_(this,7,this._anchor_7);
    this._NgIf_7_6 = new import20.Wrapper_NgIf(this._vc_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-1 col-sm-1 col-xs-1'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import22.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7_0_0:any = (0 != this.parentView.context.teamQuestionsEvaluation.length);
    this._NgIf_7_6.check_ngIf(currVal_7_0_0,throwOnChange,false);
    this._NgIf_7_6.ngDoCheck(this,this._anchor_7,throwOnChange);
    this._vc_7.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_7.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 7)) { return new View_QuestionsMasterComponent10(this.viewUtils,this,7,this._anchor_7,this._vc_7); }
    return (null as any);
  }
}
class View_QuestionsMasterComponent11 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent11,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Selecteer afbeeldingen:\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_QuestionsMasterComponent12 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  compView_7:import1.AppView<import23.QuestionsImagesComponent>;
  _QuestionsImagesComponent_7_3:import24.Wrapper_QuestionsImagesComponent;
  _text_8:any;
  _text_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_QuestionsMasterComponent12,renderType_QuestionsMasterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-1 col-sm-1 col-xs-1'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-11 col-sm-11 col-xs-11'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'questions-images',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_7 = new import24.View_QuestionsImagesComponent0(this.viewUtils,this,7,this._el_7);
    this._QuestionsImagesComponent_7_3 = new import24.Wrapper_QuestionsImagesComponent();
    this.compView_7.create(this._QuestionsImagesComponent_7_3.context);
    this._text_8 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'clickDir',(null as any)),this.eventHandler(this.handleEvent_7));
    this._QuestionsImagesComponent_7_3.subscribe(this,this.eventHandler(this.handleEvent_7),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.QuestionsImagesComponent) && (7 === requestNodeIndex))) { return this._QuestionsImagesComponent_7_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7_0_0:any = this.parentView.context.imagesAvailable;
    this._QuestionsImagesComponent_7_3.check_dir(currVal_7_0_0,throwOnChange,false);
    const currVal_7_0_1:any = this.parentView.context.imagesAvailableSet;
    this._QuestionsImagesComponent_7_3.check_dirSet(currVal_7_0_1,throwOnChange,false);
    const currVal_7_0_2:any = false;
    this._QuestionsImagesComponent_7_3.check_showDirName(currVal_7_0_2,throwOnChange,false);
    const currVal_7_0_3:any = this.parentView.context.numberOfQuestions;
    this._QuestionsImagesComponent_7_3.check_nbrQuestions(currVal_7_0_3,throwOnChange,false);
    this._QuestionsImagesComponent_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this.compView_7.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_7.destroy();
    this._QuestionsImagesComponent_7_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'clickDir')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onImagesAvailableClick($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_QuestionsMasterComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_QuestionsMasterComponent,{});
export class View_QuestionsMasterComponent0 extends import1.AppView<import0.QuestionsMasterComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _DefaultValueAccessor_29_3:import25.Wrapper_DefaultValueAccessor;
  _NumberValueAccessor_29_4:import26.Wrapper_NumberValueAccessor;
  _NG_VALUE_ACCESSOR_29_5:any[];
  _NgModel_29_6:import27.Wrapper_NgModel;
  _NgControl_29_7:any;
  _NgControlStatus_29_8:import28.Wrapper_NgControlStatus;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _vc_37:import13.ViewContainer;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import20.Wrapper_NgIf;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _vc_39:import13.ViewContainer;
  _TemplateRef_39_5:any;
  _NgIf_39_6:import20.Wrapper_NgIf;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _DefaultValueAccessor_50_3:import25.Wrapper_DefaultValueAccessor;
  _NumberValueAccessor_50_4:import26.Wrapper_NumberValueAccessor;
  _NG_VALUE_ACCESSOR_50_5:any[];
  _NgModel_50_6:import27.Wrapper_NgModel;
  _NgControl_50_7:any;
  _NgControlStatus_50_8:import28.Wrapper_NgControlStatus;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _SelectControlValueAccessor_61_3:import14.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_61_4:any[];
  _NgModel_61_5:import27.Wrapper_NgModel;
  _NgControl_61_6:any;
  _NgControlStatus_61_7:import28.Wrapper_NgControlStatus;
  _text_62:any;
  _anchor_63:any;
  /*private*/ _vc_63:import13.ViewContainer;
  _TemplateRef_63_5:any;
  _NgFor_63_6:import29.Wrapper_NgFor;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _anchor_82:any;
  /*private*/ _vc_82:import13.ViewContainer;
  _TemplateRef_82_5:any;
  _NgIf_82_6:import20.Wrapper_NgIf;
  _text_83:any;
  _anchor_84:any;
  /*private*/ _vc_84:import13.ViewContainer;
  _TemplateRef_84_5:any;
  _NgFor_84_6:import29.Wrapper_NgFor;
  _text_85:any;
  _anchor_86:any;
  /*private*/ _vc_86:import13.ViewContainer;
  _TemplateRef_86_5:any;
  _NgIf_86_6:import20.Wrapper_NgIf;
  _text_87:any;
  _anchor_88:any;
  /*private*/ _vc_88:import13.ViewContainer;
  _TemplateRef_88_5:any;
  _NgIf_88_6:import20.Wrapper_NgIf;
  _text_89:any;
  _anchor_90:any;
  /*private*/ _vc_90:import13.ViewContainer;
  _TemplateRef_90_5:any;
  _NgIf_90_6:import20.Wrapper_NgIf;
  _text_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _el_98:any;
  _el_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  compView_103:import1.AppView<import30.QuestionsBeamerComponent>;
  _QuestionsBeamerComponent_103_3:import31.Wrapper_QuestionsBeamerComponent;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  _text_107:any;
  /*private*/ _expr_151:any;
  /*private*/ _expr_152:any;
  /*private*/ _expr_153:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_QuestionsMasterComponent0,renderType_QuestionsMasterComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_151 = import16.UNINITIALIZED;
    this._expr_152 = import16.UNINITIALIZED;
    this._expr_153 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fuid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'h2',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_6,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_7,'u',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Questions',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-md-4'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'h3',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_18,'u',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Manage',(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'div',new import3.InlineArray2(2,'class','col-md-4 col-sm-3 col-xs-3'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n          Number of questions:\n        ',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_22,'div',new import3.InlineArray2(2,'class','col-md-2 col-sm-2 col-xs-2'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'input',new import3.InlineArray4(4,'class','form-control','type','number'),(null as any));
    this._DefaultValueAccessor_29_3 = new import25.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_29));
    this._NumberValueAccessor_29_4 = new import26.Wrapper_NumberValueAccessor(this.renderer,new import17.ElementRef(this._el_29));
    this._NG_VALUE_ACCESSOR_29_5 = [
      this._DefaultValueAccessor_29_3.context,
      this._NumberValueAccessor_29_4.context
    ]
    ;
    this._NgModel_29_6 = new import27.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_29_5);
    this._NgControl_29_7 = this._NgModel_29_6.context;
    this._NgControlStatus_29_8 = new import28.Wrapper_NgControlStatus(this._NgControl_29_7);
    this._text_30 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._text_31 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_22,'div',new import3.InlineArray2(2,'class','col-md-6 col-sm-6 col-xs-6'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'button',new import3.InlineArray4(4,'class','btn btn-warning','type','button'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'Configure/Reset',(null as any));
    this._text_36 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_32,(null as any));
    this._vc_37 = new import13.ViewContainer(37,32,this,this._anchor_37);
    this._TemplateRef_37_5 = new import21.TemplateRef_(this,37,this._anchor_37);
    this._NgIf_37_6 = new import20.Wrapper_NgIf(this._vc_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor(this._el_32,(null as any));
    this._vc_39 = new import13.ViewContainer(39,32,this,this._anchor_39);
    this._TemplateRef_39_5 = new import21.TemplateRef_(this,39,this._anchor_39);
    this._NgIf_39_6 = new import20.Wrapper_NgIf(this._vc_39.vcRef,this._TemplateRef_39_5);
    this._text_40 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._text_42 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'div',new import3.InlineArray2(2,'class','col-md-4 col-sm-3 col-xs-4'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n          Points per question:\n        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_43,'div',new import3.InlineArray2(2,'class','col-md-2 col-sm-2 col-xs-2'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n          ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'input',new import3.InlineArray4(4,'class','form-control','type','number'),(null as any));
    this._DefaultValueAccessor_50_3 = new import25.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_50));
    this._NumberValueAccessor_50_4 = new import26.Wrapper_NumberValueAccessor(this.renderer,new import17.ElementRef(this._el_50));
    this._NG_VALUE_ACCESSOR_50_5 = [
      this._DefaultValueAccessor_50_3.context,
      this._NumberValueAccessor_50_4.context
    ]
    ;
    this._NgModel_50_6 = new import27.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_50_5);
    this._NgControl_50_7 = this._NgModel_50_6.context;
    this._NgControlStatus_50_8 = new import28.Wrapper_NgControlStatus(this._NgControl_50_7);
    this._text_51 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._text_52 = this.renderer.createText(this._el_43,'\n      ',(null as any));
    this._text_53 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'div',new import3.InlineArray2(2,'class','col-md-4 col-sm-3 col-xs-4'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'\n          Answering mode:\n        ',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_54,'div',new import3.InlineArray2(2,'class','col-md-2 col-sm-2 col-xs-2'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'\n          ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_59,'select',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._SelectControlValueAccessor_61_3 = new import14.Wrapper_SelectControlValueAccessor(this.renderer,new import17.ElementRef(this._el_61));
    this._NG_VALUE_ACCESSOR_61_4 = [this._SelectControlValueAccessor_61_3.context];
    this._NgModel_61_5 = new import27.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_61_4);
    this._NgControl_61_6 = this._NgModel_61_5.context;
    this._NgControlStatus_61_7 = new import28.Wrapper_NgControlStatus(this._NgControl_61_6);
    this._text_62 = this.renderer.createText(this._el_61,'\n              ',(null as any));
    this._anchor_63 = this.renderer.createTemplateAnchor(this._el_61,(null as any));
    this._vc_63 = new import13.ViewContainer(63,61,this,this._anchor_63);
    this._TemplateRef_63_5 = new import21.TemplateRef_(this,63,this._anchor_63);
    this._NgFor_63_6 = new import29.Wrapper_NgFor(this._vc_63.vcRef,this._TemplateRef_63_5,this.parentView.injectorGet(import32.IterableDiffers,this.parentIndex),this.ref);
    this._text_64 = this.renderer.createText(this._el_61,'\n          ',(null as any));
    this._text_65 = this.renderer.createText(this._el_59,' \n        ',(null as any));
    this._text_66 = this.renderer.createText(this._el_54,'\n      ',(null as any));
    this._text_67 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_15,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_69 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','form-check form-check-inline'),(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'\n        ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_70,'label',new import3.InlineArray2(2,'class','form-check-label'),(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n          ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_72,'input',new import3.InlineArray16(10,'class','form-check-input','id','inlineRadioSort','name','inlineRadioAction','type','radio','value','sort'),(null as any));
    this._text_75 = this.renderer.createText(this._el_72,' Beantwoorden\n          ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_72,'input',new import3.InlineArray16(10,'class','form-check-input','id','inlineRadioResult','name','inlineRadioAction','type','radio','value','result'),(null as any));
    this._text_77 = this.renderer.createText(this._el_72,' Beoordelen\n        ',(null as any));
    this._text_78 = this.renderer.createText(this._el_70,'\n      ',(null as any));
    this._text_79 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_15,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_81 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._anchor_82 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_82 = new import13.ViewContainer(82,15,this,this._anchor_82);
    this._TemplateRef_82_5 = new import21.TemplateRef_(this,82,this._anchor_82);
    this._NgIf_82_6 = new import20.Wrapper_NgIf(this._vc_82.vcRef,this._TemplateRef_82_5);
    this._text_83 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._anchor_84 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_84 = new import13.ViewContainer(84,15,this,this._anchor_84);
    this._TemplateRef_84_5 = new import21.TemplateRef_(this,84,this._anchor_84);
    this._NgFor_84_6 = new import29.Wrapper_NgFor(this._vc_84.vcRef,this._TemplateRef_84_5,this.parentView.injectorGet(import32.IterableDiffers,this.parentIndex),this.ref);
    this._text_85 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._anchor_86 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_86 = new import13.ViewContainer(86,15,this,this._anchor_86);
    this._TemplateRef_86_5 = new import21.TemplateRef_(this,86,this._anchor_86);
    this._NgIf_86_6 = new import20.Wrapper_NgIf(this._vc_86.vcRef,this._TemplateRef_86_5);
    this._text_87 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._anchor_88 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_88 = new import13.ViewContainer(88,15,this,this._anchor_88);
    this._TemplateRef_88_5 = new import21.TemplateRef_(this,88,this._anchor_88);
    this._NgIf_88_6 = new import20.Wrapper_NgIf(this._vc_88.vcRef,this._TemplateRef_88_5);
    this._text_89 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._anchor_90 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_90 = new import13.ViewContainer(90,15,this,this._anchor_90);
    this._TemplateRef_90_5 = new import21.TemplateRef_(this,90,this._anchor_90);
    this._NgIf_90_6 = new import20.Wrapper_NgIf(this._vc_90.vcRef,this._TemplateRef_90_5);
    this._text_91 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_92 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_93 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-md-1'),(null as any));
    this._text_94 = this.renderer.createText(this._el_93,'\n    ',(null as any));
    this._text_95 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_96 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-md-7'),(null as any));
    this._text_97 = this.renderer.createText(this._el_96,'\n      ',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_96,'h3',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._el_99 = import3.createRenderElement(this.renderer,this._el_98,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_100 = import3.createRenderElement(this.renderer,this._el_99,'u',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_101 = this.renderer.createText(this._el_100,'Beamer',(null as any));
    this._text_102 = this.renderer.createText(this._el_96,'\n      ',(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_96,'questions-beamer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_103 = new import31.View_QuestionsBeamerComponent0(this.viewUtils,this,103,this._el_103);
    this._QuestionsBeamerComponent_103_3 = new import31.Wrapper_QuestionsBeamerComponent(this.parentView.injectorGet(import8.LogService,this.parentIndex),this.parentView.injectorGet(import9.ModeService,this.parentIndex),this.parentView.injectorGet(import10.WebsocketUserService,this.parentIndex));
    this.compView_103.create(this._QuestionsBeamerComponent_103_3.context);
    this._text_104 = this.renderer.createText(this._el_96,'\n    ',(null as any));
    this._text_105 = this.renderer.createText(this._el_13,'\n  ',(null as any));
    this._text_106 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_107 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_29,new import3.InlineArray8(8,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any),'change',(null as any)),this.eventHandler(this.handleEvent_29));
    this._NgModel_29_6.subscribe(this,this.eventHandler(this.handleEvent_29),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_34,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_34));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_50,new import3.InlineArray8(8,'ngModelChange',(null as any),'change',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_50));
    this._NgModel_50_6.subscribe(this,this.eventHandler(this.handleEvent_50),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_61,new import3.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_61));
    this._NgModel_61_5.subscribe(this,this.eventHandler(this.handleEvent_61),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_74,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_74));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_76,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_76));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_103,new import3.InlineArray2(2,'teamEvaluationsEvt',(null as any)),this.eventHandler(this.handleEvent_103));
    this._QuestionsBeamerComponent_103_3.subscribe(this,this.eventHandler(this.handleEvent_103),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._anchor_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._anchor_82,
      this._text_83,
      this._anchor_84,
      this._text_85,
      this._anchor_86,
      this._text_87,
      this._anchor_88,
      this._text_89,
      this._anchor_90,
      this._text_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._el_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._text_106,
      this._text_107
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.DefaultValueAccessor) && (29 === requestNodeIndex))) { return this._DefaultValueAccessor_29_3.context; }
    if (((token === import34.NumberValueAccessor) && (29 === requestNodeIndex))) { return this._NumberValueAccessor_29_4.context; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (29 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_29_5; }
    if (((token === import36.NgModel) && (29 === requestNodeIndex))) { return this._NgModel_29_6.context; }
    if (((token === import37.NgControl) && (29 === requestNodeIndex))) { return this._NgControl_29_7; }
    if (((token === import38.NgControlStatus) && (29 === requestNodeIndex))) { return this._NgControlStatus_29_8.context; }
    if (((token === import21.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import22.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6.context; }
    if (((token === import21.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import22.NgIf) && (39 === requestNodeIndex))) { return this._NgIf_39_6.context; }
    if (((token === import33.DefaultValueAccessor) && (50 === requestNodeIndex))) { return this._DefaultValueAccessor_50_3.context; }
    if (((token === import34.NumberValueAccessor) && (50 === requestNodeIndex))) { return this._NumberValueAccessor_50_4.context; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (50 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_50_5; }
    if (((token === import36.NgModel) && (50 === requestNodeIndex))) { return this._NgModel_50_6.context; }
    if (((token === import37.NgControl) && (50 === requestNodeIndex))) { return this._NgControl_50_7; }
    if (((token === import38.NgControlStatus) && (50 === requestNodeIndex))) { return this._NgControlStatus_50_8.context; }
    if (((token === import21.TemplateRef) && (63 === requestNodeIndex))) { return this._TemplateRef_63_5; }
    if (((token === import39.NgFor) && (63 === requestNodeIndex))) { return this._NgFor_63_6.context; }
    if (((token === import18.SelectControlValueAccessor) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._SelectControlValueAccessor_61_3.context; }
    if (((token === import35.NG_VALUE_ACCESSOR) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._NG_VALUE_ACCESSOR_61_4; }
    if (((token === import36.NgModel) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._NgModel_61_5.context; }
    if (((token === import37.NgControl) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._NgControl_61_6; }
    if (((token === import38.NgControlStatus) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._NgControlStatus_61_7.context; }
    if (((token === import21.TemplateRef) && (82 === requestNodeIndex))) { return this._TemplateRef_82_5; }
    if (((token === import22.NgIf) && (82 === requestNodeIndex))) { return this._NgIf_82_6.context; }
    if (((token === import21.TemplateRef) && (84 === requestNodeIndex))) { return this._TemplateRef_84_5; }
    if (((token === import39.NgFor) && (84 === requestNodeIndex))) { return this._NgFor_84_6.context; }
    if (((token === import21.TemplateRef) && (86 === requestNodeIndex))) { return this._TemplateRef_86_5; }
    if (((token === import22.NgIf) && (86 === requestNodeIndex))) { return this._NgIf_86_6.context; }
    if (((token === import21.TemplateRef) && (88 === requestNodeIndex))) { return this._TemplateRef_88_5; }
    if (((token === import22.NgIf) && (88 === requestNodeIndex))) { return this._NgIf_88_6.context; }
    if (((token === import21.TemplateRef) && (90 === requestNodeIndex))) { return this._TemplateRef_90_5; }
    if (((token === import22.NgIf) && (90 === requestNodeIndex))) { return this._NgIf_90_6.context; }
    if (((token === import30.QuestionsBeamerComponent) && (103 === requestNodeIndex))) { return this._QuestionsBeamerComponent_103_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_29_3.ngDoCheck(this,this._el_29,throwOnChange);
    this._NumberValueAccessor_29_4.ngDoCheck(this,this._el_29,throwOnChange);
    const currVal_29_2_0:any = this.context.numberOfQuestions;
    this._NgModel_29_6.check_model(currVal_29_2_0,throwOnChange,false);
    this._NgModel_29_6.ngDoCheck(this,this._el_29,throwOnChange);
    this._NgControlStatus_29_8.ngDoCheck(this,this._el_29,throwOnChange);
    const currVal_37_0_0:any = this.context.resetConfirm;
    this._NgIf_37_6.check_ngIf(currVal_37_0_0,throwOnChange,false);
    this._NgIf_37_6.ngDoCheck(this,this._anchor_37,throwOnChange);
    const currVal_39_0_0:any = this.context.resetConfirm;
    this._NgIf_39_6.check_ngIf(currVal_39_0_0,throwOnChange,false);
    this._NgIf_39_6.ngDoCheck(this,this._anchor_39,throwOnChange);
    this._DefaultValueAccessor_50_3.ngDoCheck(this,this._el_50,throwOnChange);
    this._NumberValueAccessor_50_4.ngDoCheck(this,this._el_50,throwOnChange);
    const currVal_50_2_0:any = this.context.pointsPerQuestion;
    this._NgModel_50_6.check_model(currVal_50_2_0,throwOnChange,false);
    this._NgModel_50_6.ngDoCheck(this,this._el_50,throwOnChange);
    this._NgControlStatus_50_8.ngDoCheck(this,this._el_50,throwOnChange);
    this._SelectControlValueAccessor_61_3.ngDoCheck(this,this._el_61,throwOnChange);
    const currVal_61_1_0:any = this.context.answeringType;
    this._NgModel_61_5.check_model(currVal_61_1_0,throwOnChange,false);
    this._NgModel_61_5.ngDoCheck(this,this._el_61,throwOnChange);
    this._NgControlStatus_61_7.ngDoCheck(this,this._el_61,throwOnChange);
    const currVal_63_0_0:any = this.context.answeringTypeOptions;
    this._NgFor_63_6.check_ngForOf(currVal_63_0_0,throwOnChange,false);
    this._NgFor_63_6.ngDoCheck(this,this._anchor_63,throwOnChange);
    const currVal_82_0_0:boolean = !this.context.modeAnswering;
    this._NgIf_82_6.check_ngIf(currVal_82_0_0,throwOnChange,false);
    this._NgIf_82_6.ngDoCheck(this,this._anchor_82,throwOnChange);
    const currVal_84_0_0:any = this.context.teamQuestionsEvaluation;
    this._NgFor_84_6.check_ngForOf(currVal_84_0_0,throwOnChange,false);
    this._NgFor_84_6.ngDoCheck(this,this._anchor_84,throwOnChange);
    const currVal_86_0_0:boolean = !this.context.modeAnswering;
    this._NgIf_86_6.check_ngIf(currVal_86_0_0,throwOnChange,false);
    this._NgIf_86_6.ngDoCheck(this,this._anchor_86,throwOnChange);
    const currVal_88_0_0:any = this.context.modeAnswering;
    this._NgIf_88_6.check_ngIf(currVal_88_0_0,throwOnChange,false);
    this._NgIf_88_6.ngDoCheck(this,this._anchor_88,throwOnChange);
    const currVal_90_0_0:any = this.context.modeAnswering;
    this._NgIf_90_6.check_ngIf(currVal_90_0_0,throwOnChange,false);
    this._NgIf_90_6.ngDoCheck(this,this._anchor_90,throwOnChange);
    const currVal_103_0_0:any = true;
    this._QuestionsBeamerComponent_103_3.check_inMaster(currVal_103_0_0,throwOnChange,false);
    this._QuestionsBeamerComponent_103_3.ngDoCheck(this,this._el_103,throwOnChange);
    this._vc_37.detectChangesInNestedViews(throwOnChange);
    this._vc_39.detectChangesInNestedViews(throwOnChange);
    this._vc_63.detectChangesInNestedViews(throwOnChange);
    this._vc_82.detectChangesInNestedViews(throwOnChange);
    this._vc_84.detectChangesInNestedViews(throwOnChange);
    this._vc_86.detectChangesInNestedViews(throwOnChange);
    this._vc_88.detectChangesInNestedViews(throwOnChange);
    this._vc_90.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatus_29_8.checkHost(this,this,this._el_29,throwOnChange);
    const currVal_151:any = this.context.resetConfirm;
    if (import3.checkBinding(throwOnChange,this._expr_151,currVal_151)) {
      this.renderer.setElementProperty(this._el_34,'disabled',currVal_151);
      this._expr_151 = currVal_151;
    }
    this._NgControlStatus_50_8.checkHost(this,this,this._el_50,throwOnChange);
    this._NgControlStatus_61_7.checkHost(this,this,this._el_61,throwOnChange);
    const currVal_152:any = this.context.modeAnswering;
    if (import3.checkBinding(throwOnChange,this._expr_152,currVal_152)) {
      this.renderer.setElementProperty(this._el_74,'checked',currVal_152);
      this._expr_152 = currVal_152;
    }
    const currVal_153:boolean = !this.context.modeAnswering;
    if (import3.checkBinding(throwOnChange,this._expr_153,currVal_153)) {
      this.renderer.setElementProperty(this._el_76,'checked',currVal_153);
      this._expr_153 = currVal_153;
    }
    this.compView_103.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_37.destroyNestedViews();
    this._vc_39.destroyNestedViews();
    this._vc_63.destroyNestedViews();
    this._vc_82.destroyNestedViews();
    this._vc_84.destroyNestedViews();
    this._vc_86.destroyNestedViews();
    this._vc_88.destroyNestedViews();
    this._vc_90.destroyNestedViews();
    this.compView_103.destroy();
    this._NgModel_29_6.ngOnDestroy();
    this._NgModel_50_6.ngOnDestroy();
    this._NgModel_61_5.ngOnDestroy();
    this._QuestionsBeamerComponent_103_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 37)) { return new View_QuestionsMasterComponent1(this.viewUtils,this,37,this._anchor_37,this._vc_37); }
    if ((nodeIndex == 39)) { return new View_QuestionsMasterComponent2(this.viewUtils,this,39,this._anchor_39,this._vc_39); }
    if ((nodeIndex == 63)) { return new View_QuestionsMasterComponent3(this.viewUtils,this,63,this._anchor_63,this._vc_63); }
    if ((nodeIndex == 82)) { return new View_QuestionsMasterComponent4(this.viewUtils,this,82,this._anchor_82,this._vc_82); }
    if ((nodeIndex == 84)) { return new View_QuestionsMasterComponent5(this.viewUtils,this,84,this._anchor_84,this._vc_84); }
    if ((nodeIndex == 86)) { return new View_QuestionsMasterComponent9(this.viewUtils,this,86,this._anchor_86,this._vc_86); }
    if ((nodeIndex == 88)) { return new View_QuestionsMasterComponent11(this.viewUtils,this,88,this._anchor_88,this._vc_88); }
    if ((nodeIndex == 90)) { return new View_QuestionsMasterComponent12(this.viewUtils,this,90,this._anchor_90,this._vc_90); }
    return (null as any);
  }
  handleEvent_29(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_29_3.handleEvent(eventName,$event) && result);
    result = (this._NumberValueAccessor_29_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.numberOfQuestions = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_34(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickSetNumberOfQuestionsOne()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_50(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_50_3.handleEvent(eventName,$event) && result);
    result = (this._NumberValueAccessor_50_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.pointsPerQuestion = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'change')) {
      const pd_sub_1:any = ((<any>this.context.onPointsPerQuestionChange($event.target.value)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_61(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_61_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.answeringType = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_74(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickRadioAction(true)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_76(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickRadioAction(false)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_103(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'teamEvaluationsEvt')) {
      const pd_sub_0:any = ((<any>this.context.onTeamEvaluationsEvt($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}