/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/routes/test/test.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/services/websocket.user.service';
import * as import9 from '../../../../../src/app/components/image-local/image-local.component';
import * as import10 from '../../components/image-local/image-local.component.ngfactory';
import * as import11 from '../../../../../src/app/services/cloud.service';
export class Wrapper_TestComponent {
  /*private*/ _eventHandler:Function;
  context:import0.TestComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.TestComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_TestComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_TestComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.TestComponent>;
  _TestComponent_0_3:Wrapper_TestComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TestComponent_Host0,renderType_TestComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'test',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TestComponent0(this.viewUtils,this,0,this._el_0);
    this._TestComponent_0_3 = new Wrapper_TestComponent(this.injectorGet(import8.WebsocketUserService,this.parentIndex));
    this.compView_0.create(this._TestComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._TestComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TestComponent) && (0 === requestNodeIndex))) { return this._TestComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TestComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TestComponentNgFactory:import7.ComponentFactory<import0.TestComponent> = new import7.ComponentFactory<import0.TestComponent>('test',View_TestComponent_Host0,import0.TestComponent);
const styles_TestComponent:any[] = ([] as any[]);
var renderType_TestComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_TestComponent,{});
export class View_TestComponent0 extends import1.AppView<import0.TestComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import9.ImageLocalComponent>;
  _ImageLocalComponent_5_3:import10.Wrapper_ImageLocalComponent;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TestComponent0,renderType_TestComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Test',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'image-local',new import3.InlineArray8(6,'height','261','source','testbeeld.png','width','333'),(null as any));
    this.compView_5 = new import10.View_ImageLocalComponent0(this.viewUtils,this,5,this._el_5);
    this._ImageLocalComponent_5_3 = new import10.Wrapper_ImageLocalComponent(this.parentView.injectorGet(import11.CloudService,this.parentIndex));
    this.compView_5.create(this._ImageLocalComponent_5_3.context);
    this._text_6 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.ImageLocalComponent) && (5 === requestNodeIndex))) { return this._ImageLocalComponent_5_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5_0_0:any = 'testbeeld.png';
    this._ImageLocalComponent_5_3.check_source(currVal_5_0_0,throwOnChange,false);
    const currVal_5_0_1:any = '261';
    this._ImageLocalComponent_5_3.check_height(currVal_5_0_1,throwOnChange,false);
    const currVal_5_0_2:any = '333';
    this._ImageLocalComponent_5_3.check_width(currVal_5_0_2,throwOnChange,false);
    this._ImageLocalComponent_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this.compView_5.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_5.destroy();
    this._ImageLocalComponent_5_3.ngOnDestroy();
  }
}