/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/routes/configuration/configuration.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../../../../src/app/services/websocket.user.service';
import * as import10 from '../../../../../src/app/services/cloud.service';
import * as import11 from '@angular/common/src/location/location';
import * as import12 from './configuration.component.css.shim.ngstyle';
import * as import13 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import17 from '@angular/core/src/change_detection/change_detection_util';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/forms/src/directives/default_value_accessor';
import * as import20 from '@angular/forms/src/directives/validators';
import * as import21 from '@angular/forms/src/validators';
import * as import22 from '@angular/forms/src/directives/control_value_accessor';
import * as import23 from '@angular/forms/src/directives/ng_model';
import * as import24 from '@angular/forms/src/directives/ng_control';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_ConfigurationComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ConfigurationComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.ConfigurationComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ConfigurationComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ConfigurationComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ConfigurationComponent>;
  _ConfigurationComponent_0_3:Wrapper_ConfigurationComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ConfigurationComponent_Host0,renderType_ConfigurationComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'configuration',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ConfigurationComponent0(this.viewUtils,this,0,this._el_0);
    this._ConfigurationComponent_0_3 = new Wrapper_ConfigurationComponent(this.injectorGet(import8.Router,this.parentIndex),this.injectorGet(import9.WebsocketUserService,this.parentIndex),this.injectorGet(import10.CloudService,this.parentIndex),this.injectorGet(import11.Location,this.parentIndex));
    this.compView_0.create(this._ConfigurationComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ConfigurationComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ConfigurationComponent) && (0 === requestNodeIndex))) { return this._ConfigurationComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ConfigurationComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ConfigurationComponentNgFactory:import7.ComponentFactory<import0.ConfigurationComponent> = new import7.ComponentFactory<import0.ConfigurationComponent>('configuration',View_ConfigurationComponent_Host0,import0.ConfigurationComponent);
const styles_ConfigurationComponent:any[] = [import12.styles];
var renderType_ConfigurationComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ConfigurationComponent,{});
export class View_ConfigurationComponent0 extends import1.AppView<import0.ConfigurationComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import13.Wrapper_DefaultValueAccessor;
  _RequiredValidator_23_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_23_5:any[];
  _NG_VALUE_ACCESSOR_23_6:any[];
  _NgModel_23_7:import15.Wrapper_NgModel;
  _NgControl_23_8:any;
  _NgControlStatus_23_9:import16.Wrapper_NgControlStatus;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ConfigurationComponent0,renderType_ConfigurationComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_65 = import17.UNINITIALIZED;
    this._expr_66 = import17.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','col-xs-12 text-center'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Configureer',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._text_11 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','form-group row'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','col-lg-3 col-md-2 col-sm-3 col-xs-3'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n        Websocket server:\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','col-lg-4 col-md-6 col-sm-6 col-xs-6'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','inner-addon left-addon'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'i',new import3.InlineArray2(2,'class','glyphicon glyphicon-signal'),(null as any));
    this._text_22 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_19,'input',new import3.InlineArray16(10,'class','form-control','id','wsServer','name','wsServer','required','','type','text'),(null as any));
    this._DefaultValueAccessor_23_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_23));
    this._RequiredValidator_23_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_23_5 = [this._RequiredValidator_23_4.context];
    this._NG_VALUE_ACCESSOR_23_6 = [this._DefaultValueAccessor_23_3.context];
    this._NgModel_23_7 = new import15.Wrapper_NgModel((null as any),this._NG_VALIDATORS_23_5,(null as any),this._NG_VALUE_ACCESSOR_23_6);
    this._NgControl_23_8 = this._NgModel_23_7.context;
    this._NgControlStatus_23_9 = new import16.Wrapper_NgControlStatus(this._NgControl_23_8);
    this._text_24 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n            Ongeldig IP adres.\n        ',(null as any));
    this._text_28 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','col-lg-3 col-md-2 col-sm-3 col-xs-3'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._text_33 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n    ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','col-xs-12 text-center'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'Configureer',(null as any));
    this._text_40 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_36,'button',new import3.InlineArray2(2,'class','btn btn-warning'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Cancel',(null as any));
    this._text_43 = this.renderer.createText(this._el_36,'\n    ',(null as any));
    this._text_44 = this.renderer.createText(this._el_34,'\n  ',(null as any));
    this._text_45 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_1,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_47 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n    ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'div',new import3.InlineArray2(2,'class','col-xs-12 text-center'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n        ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'button',new import3.InlineArray2(2,'class','btn btn-danger'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Zet standaard waarden terug',(null as any));
    this._text_54 = this.renderer.createText(this._el_50,'\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_48,'\n  ',(null as any));
    this._text_56 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_57 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray8(8,'ngModelChange',(null as any),'keyup',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_23));
    this._NgModel_23_7.subscribe(this,this.eventHandler(this.handleEvent_23),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_38,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_38));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_41,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_41));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_52,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_52));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3.context; }
    if (((token === import20.RequiredValidator) && (23 === requestNodeIndex))) { return this._RequiredValidator_23_4.context; }
    if (((token === import21.NG_VALIDATORS) && (23 === requestNodeIndex))) { return this._NG_VALIDATORS_23_5; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_6; }
    if (((token === import23.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_7.context; }
    if (((token === import24.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_8; }
    if (((token === import25.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_9.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_1_0:any = '';
    this._RequiredValidator_23_4.check_required(currVal_23_1_0,throwOnChange,false);
    this._RequiredValidator_23_4.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_2_0:any = 'wsServer';
    this._NgModel_23_7.check_name(currVal_23_2_0,throwOnChange,false);
    const currVal_23_2_1:any = this.context.wsServer;
    this._NgModel_23_7.check_model(currVal_23_2_1,throwOnChange,false);
    this._NgModel_23_7.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.ngDoCheck(this,this._el_23,throwOnChange);
    this._RequiredValidator_23_4.checkHost(this,this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.checkHost(this,this,this._el_23,throwOnChange);
    const currVal_65:any = this.context.wsServerValid;
    if (import3.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementProperty(this._el_26,'hidden',currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:boolean = !this.context.wsServerValid;
    if (import3.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementProperty(this._el_38,'disabled',currVal_66);
      this._expr_66 = currVal_66;
    }
  }
  destroyInternal():void {
    this._NgModel_23_7.ngOnDestroy();
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_23_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.wsServer = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'keyup')) {
      const pd_sub_1:any = ((<any>this.context.onWsServerChanged($event.target.value)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_38(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onConfigure()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_41(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onCancel()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_52(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onDefault()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}